<a href="https://colab.research.google.com/github/Mirazsarker18/Bpl-team-make-project/blob/main/first_practice_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

## Series

In [ ]:
sales = pd.Series(
    [50000, 40000, 80000, 60000],
    index = ["Dhaka", "Commilla", "Gazipur", "sylet"],
    name = "daily sales update report BDT",
)

print(sales)

Dhaka       50000
Commilla    40000
Gazipur     80000
sylet       60000
Name: daily sales update report BDT, dtype: int64

In [ ]:
print(sales.name)
print(sales.values)
print(sales.index)
print(sales.dtype)
print(sales.size)
print(sales.shape)
print(sales.ndim)
print(sales.nbytes)
print(sales.max())

daily sales update report BDT
[50000 40000 80000 60000]
Index(['Dhaka', 'Commilla', 'Gazipur', 'sylet'], dtype='object')
int64
4
(4,)
1
32
80000

In [ ]:
print(sales.min())
print(sales.mean())

40000
57500.0

## DataFrame

In [ ]:
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106],
    "customer_name": ["Hassan", "Karim", "Raju", "Rana", "Kuddus", "Rafi"],
    "city": ["Dhaka", "Khulna", "Gazipur", "Rangpur", "Dhaka", "Khulna"],
    "product": ["Phone", "Laptop", "Shoes", "Watch", "Laptop", "Phone"],
    "price": [100000, 50000, 30000, 10000, 60000, 65000],
    "quantity": [2, 1, 10, 5, 1, 1],
    "total": [200000, 50000, 300000, 50000, 60000, 65000]
})
print(orders)

   order_id customer_name     city product   price  quantity   total
0       101        Hassan    Dhaka   Phone  100000         2  200000
1       102         Karim   Khulna  Laptop   50000         1   50000
2       103          Raju  Gazipur   Shoes   30000        10  300000
3       104          Rana  Rangpur   Watch   10000         5   50000
4       105        Kuddus    Dhaka  Laptop   60000         1   60000
5       106          Rafi   Khulna   Phone   65000         1   65000

In [ ]:
print(orders.shape)
print(orders.columns)
print(orders.size)
print(orders.ndim)
print(orders.info())

(6, 7)
Index(['order_id', 'customer_name', 'city', 'product', 'price', 'quantity',
       'total'],
      dtype='object')
42
2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       6 non-null      int64
 1   customer_name  6 non-null      object
 2   city           6 non-null      object
 3   product        6 non-null      object
 4   price          6 non-null      int64
 5   quantity       6 non-null      int64
 6   total          6 non-null      int64
dtypes: int64(4), object(3)
memory usage: 468.0+ bytes
None

In [ ]:
print(orders.describe())

         order_id          price   quantity          total
count    6.000000       6.000000   6.000000       6.000000
mean   103.500000   52500.000000   3.333333  120833.333333
std      1.870829   30943.496894   3.614784  105091.230208
min    101.000000   10000.000000   1.000000   50000.000000
25%    102.250000   35000.000000   1.000000   52500.000000
50%    103.500000   55000.000000   1.500000   62500.000000
75%    104.750000   63750.000000   4.250000  166250.000000
max    106.000000  100000.000000  10.000000  300000.000000

## loc and iloc

In [ ]:
print(orders)

   order_id customer_name     city product   price  quantity   total
0       101        Hassan    Dhaka   Phone  100000         2  200000
1       102         Karim   Khulna  Laptop   50000         1   50000
2       103          Raju  Gazipur   Shoes   30000        10  300000
3       104          Rana  Rangpur   Watch   10000         5   50000
4       105        Kuddus    Dhaka  Laptop   60000         1   60000
5       106          Rafi   Khulna   Phone   65000         1   65000

In [ ]:
orders.loc[2]

order_id             103
customer_name       Raju
city             Gazipur
product            Shoes
price              30000
quantity              10
total             300000
Name: 2, dtype: object

In [ ]:
orders.loc[2, "customer_name"]
orders.loc[:6, ["order_id", "customer_name", "city", "product", "price", "quantity", "total"]]

   order_id customer_name     city product   price  quantity   total
0       101        Hassan    Dhaka   Phone  100000         2  200000
1       102         Karim   Khulna  Laptop   50000         1   50000
2       103          Raju  Gazipur   Shoes   30000        10  300000
3       104          Rana  Rangpur   Watch   10000         5   50000
4       105        Kuddus    Dhaka  Laptop   60000         1   60000
5       106          Rafi   Khulna   Phone   65000         1   65000

In [ ]:
orders.iloc[:5, :7]

   order_id customer_name     city product   price  quantity   total
0       101        Hassan    Dhaka   Phone  100000         2  200000
1       102         Karim   Khulna  Laptop   50000         1   50000
2       103          Raju  Gazipur   Shoes   30000        10  300000
3       104          Rana  Rangpur   Watch   10000         5   50000
4       105        Kuddus    Dhaka  Laptop   60000         1   60000

In [ ]:
print(orders)

   order_id customer_name     city product   price  quantity   total
0       101        Hassan    Dhaka   Phone  100000         2  200000
1       102         Karim   Khulna  Laptop   50000         1   50000
2       103          Raju  Gazipur   Shoes   30000        10  300000
3       104          Rana  Rangpur   Watch   10000         5   50000
4       105        Kuddus    Dhaka  Laptop   60000         1   60000
5       106          Rafi   Khulna   Phone   65000         1   65000

## Filtering

In [ ]:
# City order list
dhaka_orders = orders[orders["city"] == "Dhaka"]
print(dhaka_orders)

   order_id customer_name   city product   price  quantity   total
0       101        Hassan  Dhaka   Phone  100000         2  200000
4       105        Kuddus  Dhaka  Laptop   60000         1   60000

In [ ]:
# list of orders 50000 over
orders_price = orders[orders["price"] > 50000]
print(orders_price)

   order_id customer_name    city product   price  quantity   total
0       101        Hassan   Dhaka   Phone  100000         2  200000
4       105        Kuddus   Dhaka  Laptop   60000         1   60000
5       106          Rafi  Khulna   Phone   65000         1   65000

In [ ]:
# city and 50000 over orders
orders_result = orders[(orders["city"] == "Dhaka") | (orders["city"] == "Khulna") & (orders["price"] > 20000)]
print(orders_result)

   order_id customer_name    city product   price  quantity   total
0       101        Hassan   Dhaka   Phone  100000         2  200000
1       102         Karim  Khulna  Laptop   50000         1   50000
4       105        Kuddus   Dhaka  Laptop   60000         1   60000
5       106          Rafi  Khulna   Phone   65000         1   65000

In [ ]:
order_result = orders[(orders["city"] == "Dhaka") | (orders["city"] == "Khulna") | (orders["city"] == "Gazipur") & (orders["price"] > 50000) | (orders["price"] <= 10000)]
print(order_result)

   order_id customer_name     city product   price  quantity   total
0       101        Hassan    Dhaka   Phone  100000         2  200000
1       102         Karim   Khulna  Laptop   50000         1   50000
3       104          Rana  Rangpur   Watch   10000         5   50000
4       105        Kuddus    Dhaka  Laptop   60000         1   60000
5       106          Rafi   Khulna   Phone   65000         1   65000

In [ ]:
#isin function
orders[orders["city"].isin(["Dhaka", "Gazipur"])]

   order_id customer_name     city product   price  quantity   total
0       101        Hassan    Dhaka   Phone  100000         2  200000
2       103          Raju  Gazipur   Shoes   30000        10  300000
4       105        Kuddus    Dhaka  Laptop   60000         1   60000

In [ ]:
orders[orders["city"].isin(["Khulna", "Gazipur"])]

   order_id customer_name     city product  price  quantity   total
1       102         Karim   Khulna  Laptop  50000         1   50000
2       103          Raju  Gazipur   Shoes  30000        10  300000
5       106          Rafi   Khulna   Phone  65000         1   65000

## GroupBy

In [ ]:
city_result = orders.groupby("city")["price"].sum()
print(city_result)

city
Dhaka      160000
Gazipur     30000
Khulna     115000
Rangpur     10000
Name: price, dtype: int64

In [ ]:
orders.groupby("city")["total"].agg(["sum", "mean", "min", "max", "count"])

            sum      mean     min     max  count
city
Dhaka    260000  130000.0   60000  200000      2
Gazipur  300000  300000.0  300000  300000      1
Khulna   115000   57500.0   50000   65000      2
Rangpur   50000   50000.0   50000   50000      1

In [ ]:
print(orders)

   order_id customer_name     city product   price  quantity   total
0       101        Hassan    Dhaka   Phone  100000         2  200000
1       102         Karim   Khulna  Laptop   50000         1   50000
2       103          Raju  Gazipur   Shoes   30000        10  300000
3       104          Rana  Rangpur   Watch   10000         5   50000
4       105        Kuddus    Dhaka  Laptop   60000         1   60000
5       106          Rafi   Khulna   Phone   65000         1   65000

In [ ]:
orders.groupby("customer_name")["order_id"].count()

customer_name
Hassan    1
Karim     1
Kuddus    1
Rafi      1
Raju      1
Rana      1
Name: order_id, dtype: int64

In [ ]:
orders.groupby("customer_name")["total"].sum()

customer_name
Hassan    200000
Karim      50000
Kuddus     60000
Rafi       65000
Raju      300000
Rana       50000
Name: total, dtype: int64

## Merge / Join

In [ ]:
customers = pd.DataFrame({
"customer_name": ["Hassan","Karim","Raju","Rafi","Rana"],
"phone": ["017xxxxxxx1","018xxxxxxx2","019xxxxxxx3","015xxxxxxx4","016xxxxxxx5"],
"membership": ["Gold","Silver","Silver","Gold","Bronze"]
})

In [ ]:
full_data = pd.merge(orders, customers, on='customer_name', how="left")
print(full_data)

   order_id customer_name     city product   price  quantity   total  \
0       101        Hassan    Dhaka   Phone  100000         2  200000
1       102         Karim   Khulna  Laptop   50000         1   50000
2       103          Raju  Gazipur   Shoes   30000        10  300000
3       104          Rana  Rangpur   Watch   10000         5   50000
4       105        Kuddus    Dhaka  Laptop   60000         1   60000
5       106          Rafi   Khulna   Phone   65000         1   65000

         phone membership
0  017xxxxxxx1       Gold
1  018xxxxxxx2     Silver
2  019xxxxxxx3     Silver
3  016xxxxxxx5     Bronze
4          NaN        NaN
5  015xxxxxxx4       Gold

In [ ]:
full_data.groupby("membership")["price"].sum()

membership
Bronze     10000
Gold      165000
Silver     80000
Name: price, dtype: int64

# Home Work - Class 06

In [ ]:
students = pd.DataFrame({
"student_id": [1,2,3,4,5,6,7,8],
"name": ["Alif","Meherin","Tanvir","Priya",
"Sadman","Lamia","Fahim","Ruma"],
"district": ["Dhaka","Sylhet","Dhaka","Chittagong",
"Sylhet","Dhaka","Chittagong","Sylhet"],
"subject": ["Math","Physics","Math","Chemistry",
"Math","Physics","Math","Chemistry"],
"marks": [78, 65, 91, 55, 82, 47, 88, 73]
})
teachers = pd.DataFrame({
"subject": ["Math","Physics","Chemistry"],
"teacher": ["Rahman Sir","Nusrat Ma'am","Kamal Sir"]
})

print(students)
print(teachers)

   student_id     name    district    subject  marks
0           1     Alif       Dhaka       Math     78
1           2  Meherin      Sylhet    Physics     65
2           3   Tanvir       Dhaka       Math     91
3           4    Priya  Chittagong  Chemistry     55
4           5   Sadman      Sylhet       Math     82
5           6    Lamia       Dhaka    Physics     47
6           7    Fahim  Chittagong       Math     88
7           8     Ruma      Sylhet  Chemistry     73
     subject       teacher
0       Math    Rahman Sir
1    Physics  Nusrat Ma'am
2  Chemistry     Kamal Sir

## Q1

In [ ]:
student_series = pd.Series(students["marks"])
print(student_series)

0    78
1    65
2    91
3    55
4    82
5    47
6    88
7    73
Name: marks, dtype: int64

In [ ]:
student_series.max()

91

In [ ]:
student_series.min()

47

In [ ]:
print(student_series.mean())

72.375

## Q2

In [ ]:
print(students)

   student_id     name    district    subject  marks
0           1     Alif       Dhaka       Math     78
1           2  Meherin      Sylhet    Physics     65
2           3   Tanvir       Dhaka       Math     91
3           4    Priya  Chittagong  Chemistry     55
4           5   Sadman      Sylhet       Math     82
5           6    Lamia       Dhaka    Physics     47
6           7    Fahim  Chittagong       Math     88
7           8     Ruma      Sylhet  Chemistry     73

In [ ]:
loc_info = students.loc[2, ["student_id", "name", "district", "subject", "marks"]]
print(loc_info)

student_id         3
name          Tanvir
district       Dhaka
subject         Math
marks             91
Name: 2, dtype: object

In [ ]:
iloc_info = students.iloc[:3, [1, 4]]
print(iloc_info)

      name  marks
0     Alif     78
1  Meherin     65
2   Tanvir     91

## Q3

In [ ]:
print(students)

   student_id     name    district    subject  marks
0           1     Alif       Dhaka       Math     78
1           2  Meherin      Sylhet    Physics     65
2           3   Tanvir       Dhaka       Math     91
3           4    Priya  Chittagong  Chemistry     55
4           5   Sadman      Sylhet       Math     82
5           6    Lamia       Dhaka    Physics     47
6           7    Fahim  Chittagong       Math     88
7           8     Ruma      Sylhet  Chemistry     73

In [ ]:
students[(students["district"] == 'Dhaka') & (students["marks"] > 70)]

   student_id    name district subject  marks
0           1    Alif    Dhaka    Math     78
2           3  Tanvir    Dhaka    Math     91

## Q4

In [ ]:
students[students["subject"].isin(["Math", "Physics"])]

   student_id     name    district  subject  marks
0           1     Alif       Dhaka     Math     78
1           2  Meherin      Sylhet  Physics     65
2           3   Tanvir       Dhaka     Math     91
4           5   Sadman      Sylhet     Math     82
5           6    Lamia       Dhaka  Physics     47
6           7    Fahim  Chittagong     Math     88

## Q5

In [ ]:
student_mean = students.groupby("district")["marks"].mean()
print(student_mean)

district
Chittagong    71.500000
Dhaka         72.000000
Sylhet        73.333333
Name: marks, dtype: float64

## Q6 is pending

## Q7

In [ ]:
print(teachers)

     subject       teacher
0       Math    Rahman Sir
1    Physics  Nusrat Ma'am
2  Chemistry     Kamal Sir

In [ ]:
student_data = pd.merge(students, teachers, on="subject", how="inner")
print(student_data)

   student_id     name    district    subject  marks       teacher
0           1     Alif       Dhaka       Math     78    Rahman Sir
1           2  Meherin      Sylhet    Physics     65  Nusrat Ma'am
2           3   Tanvir       Dhaka       Math     91    Rahman Sir
3           4    Priya  Chittagong  Chemistry     55     Kamal Sir
4           5   Sadman      Sylhet       Math     82    Rahman Sir
5           6    Lamia       Dhaka    Physics     47  Nusrat Ma'am
6           7    Fahim  Chittagong       Math     88    Rahman Sir
7           8     Ruma      Sylhet  Chemistry     73     Kamal Sir

In [ ]:
avg_mark = student_data.groupby("teacher")["marks"].mean().idxmax()
print(avg_mark)

Rahman Sir